export enum Handlers {
  COUNTER_HANDLER = 'COUNTER_HANDLER',
  HINTS_HANDLER = 'HINTS_HANDLER',
  QUESTION_UPDATE_HANDLER = 'QUESTION_UPDATE_HANDLER',
  UPLOADING_ANSWER_HANDLER = 'UPLOADING_ANSWER_HANDLER',
  REQUESTING_QUESTION_HANDLER = 'REQUESTING_QUESTION_HANDLER'
}
