export enum GlobalHandler {
    MENU_HANDLER = 'MENU_HANDLER',
    MENU_ALERT_HANDLER = 'MENU_ALERT_HANDLER',
    CLEAR_MENU_ALERT_HANDLER = 'CLEAR_MENU_ALERT_HANDLER',
    USER_HANDLER = 'USER_HANDLER',
    GAME_HANDLER = 'GAME_HANDLER',
    ALERT_HANDLER = 'ALERT_HANDLER',
    CLEAR_ALERT_HANDLER = 'CLEAR_ALERT_HANDLER'
}