export enum Handlers {
    DISPLAY_HANDLER = 'DISPLAY_HANDLER',
    SET_MODE_HANDLER = 'SET_MODE_HANDLER',
    RECOVERY_HANDLER = 'RECOVERY_HANDLER',
    RECOVERY_SUCCESS_HANDLER = 'RECOVERY_SUCCESS_HANDLER',
    FETCHED_DATA_HANDLER = 'FETCHED_DATA_HANDLER'
  }