export enum Handlers {
  UPDATE_PLAYERS_HANDLERS = 'UPDATE_PLAYERS_HANDLERS',
  BUTTON_HANDLER = 'BUTTON_HANDLER',
  HEADER_HANDLER = 'HEADER_HANDLER',
  COUNTER_HANDLER = 'COUNTER_HANDLER',
  HINTS_HANDLER = 'HINTS_HANDLER',
  ON_GET_READY_SOCKET_HANDLER = 'ON_GET_READY_SOCKET_HANDLER',
  ON_QUESTION_SOCKET_HANDLER = 'ON_QUESTION_SOCKET_HANDLER',
  RESULTS_ON_DISPLAY_HANDLER = 'RESULTS_ON_DISPLAY_HANDLER',
  RESULTS_HANDLER = 'RESULTS_HANDLER'
}
