export enum Handlers {
  ON_OPEN_ROOM_HANDLER = 'ON_OPEN_ROOM_HANDLER',
  UPDATE_PLAYERS_HANDLERS = 'UPDATE_PLAYERS_HANDLERS',
  START_GAME_REQ_HANDLER = 'START_GAME_REQ_HANDLER',
  HEADER_DISPLAY_HANDLER = 'HEADER_DISPLAY_HANDLER',
  COUNTER_HANDLER = 'COUNTER_HANDLER',
  COUNTER_STATUS_HANDLER = 'COUNTER_STATUS_HANDLER',
  COUNTER_ROUND_HANDLER = 'COUNTER_ROUND_HANDLER',
  SOCKET_GET_READY_HANDLER = 'SOCKET_GET_READY_HANDLER',
  SOCKET_HOST_QUESTION_HANDLER = 'SOCKET_HOST_QUESTION_HANDLER',
  RESULTS_ON_DISPLAY_HANDLER = 'RESULTS_ON_DISPLAY_HANDLER',
  RESULTS_HANDLER = 'RESULTS_HANDLER'
}
