export enum Handlers {
    GAMEMODE_HANDLER = 'GAMEMODE_HANDLER',
    NICKNAME_HANDLER = 'NICKNAME_HANDLER',
    TIMER_HANDLER = 'TIMER_HANDLER',
    LEVEL_HANDLER = 'LEVEL_HANDLER',
    QUANTITY_HANDLER = 'QUANTITY_HANDLER'
}